CREATE TYPE Financial.CashflowTVP AS TABLE
(
    FiscalDateEnding DATE NOT NULL,
    ReportedCurrency VARCHAR(10) NOT NULL,
    OperatingCashflow BIGINT NULL,
    PaymentsForOperatingActivities BIGINT NULL,
    ProceedsFromOperatingActivities BIGINT NULL,
    ChangeInOperatingLiabilities BIGINT NULL,
    ChangeInOperatingAssets BIGINT NULL,
    DepreciationDepletionAndAmortization BIGINT NULL,
    CapitalExpenditures BIGINT NULL,
    ChangeInReceivables BIGINT NULL,
    ChangeInInventory BIGINT NULL,
    ProfitLoss BIGINT NULL,
    CashflowFromInvestment BIGINT NULL,
    CashflowFromFinancing BIGINT NULL,
    ProceedsFromRepaymentsOfShortTermDebt BIGINT NULL,
    PaymentsForRepurchaseOfCommonStock BIGINT NULL,
    PaymentsForRepurchaseOfEquity BIGINT NULL,
    PaymentsForRepurchaseOfPreferredStock BIGINT NULL,
    DividendPayout BIGINT NULL,
    DividendPayoutCommonStock BIGINT NULL,
    DividendPayoutPreferredStock BIGINT NULL,
    ProceedsFromIssuanceOfCommonStock BIGINT NULL,
    ProceedsFromIssuanceOfLongTermDebtAndCapitalSecuritiesNet BIGINT NULL,
    ProceedsFromIssuanceOfPreferredStock BIGINT NULL,
    ProceedsFromRepurchaseOfEquity BIGINT NULL,
    ProceedsFromSaleOfTreasuryStock BIGINT NULL,
    ChangeInCashAndCashEquivalents BIGINT NULL,
    ChangeInExchangeRate BIGINT NULL,
    NetIncome BIGINT NULL
)
