CREATE TYPE Financial.IncomeStatementTVP AS TABLE
(
    FiscalDateEnding DATE,
    ReportedCurrency NVARCHAR(10),
    GrossProfit BIGINT,
    TotalRevenue BIGINT,
    CostOfRevenue BIGINT,
    CostOfGoodsAndServicesSold BIGINT,
    OperatingIncome BIGINT,
    SellingGeneralAndAdministrative BIGINT,
    ResearchAndDevelopment BIGINT,
    OperatingExpenses BIGINT,
    InvestmentIncomeNet BIGINT,
    NetInterestIncome BIGINT,
    InterestIncome BIGINT,
    InterestExpense BIGINT,
    NonInterestIncome BIGINT,
    OtherNonOperatingIncome BIGINT,
    Depreciation BIGINT,
    DepreciationAndAmortization BIGINT,
    IncomeBeforeTax BIGINT,
    IncomeTaxExpense BIGINT,
    InterestAndDebtExpense BIGINT,
    NetIncomeFromContinuingOperations BIGINT,
    ComprehensiveIncomeNetOfTax BIGINT,
    Ebit BIGINT,
    Ebitda BIGINT,
    NetIncome BIGINT
)
