 CREATE TABLE Financial.BalanceSheet
(
    Id INT PRIMARY KEY IDENTITY(1,1), 
    StockId INT NOT NULL,
    FiscalDateEnding DATE NOT NULL,
    ReportedCurrency VARCHAR(10) NOT NULL,
    TotalAssets DECIMAL(15,2) NULL,
    TotalCurrentAssets DECIMAL(15,2) NULL,
    CashAndCashEquivalentsAtCarryingValue DECIMAL(15,2) NULL,
    CashAndShortTermInvestments DECIMAL(15,2) NULL,
    Inventory DECIMAL(15,2) NULL,
    CurrentNetReceivables DECIMAL(15,2) NULL,
    TotalNonCurrentAssets DECIMAL(15,2) NULL,
    PropertyPlantEquipment DECIMAL(15,2) NULL,
    AccumulatedDepreciationAmortizationPPE DECIMAL(15,2) NULL,
    IntangibleAssets DECIMAL(15,2) NULL,
    IntangibleAssetsExcludingGoodwill DECIMAL(15,2) NULL,
    Goodwill DECIMAL(15,2) NULL,
    Investments DECIMAL(15,2) NULL,
    LongTermInvestments DECIMAL(15,2) NULL,
    ShortTermInvestments DECIMAL(15,2) NULL,
    OtherCurrentAssets DECIMAL(15,2) NULL,
    OtherNonCurrentAssets DECIMAL(15,2) NULL,
    TotalLiabilities DECIMAL(15,2) NULL,
    TotalCurrentLiabilities DECIMAL(15,2) NULL,
    CurrentAccountsPayable DECIMAL(15,2) NULL,
    DeferredRevenue DECIMAL(15,2) NULL,
    CurrentDebt DECIMAL(15,2) NULL,
    ShortTermDebt DECIMAL(15,2) NULL,
    TotalNonCurrentLiabilities DECIMAL(15,2) NULL,
    CapitalLeaseObligations DECIMAL(15,2) NULL,
    LongTermDebt DECIMAL(15,2) NULL,
    CurrentLongTermDebt DECIMAL(15,2) NULL,
    LongTermDebtNoncurrent DECIMAL(15,2) NULL,
    ShortLongTermDebtTotal DECIMAL(15,2) NULL,
    OtherCurrentLiabilities DECIMAL(15,2) NULL,
    OtherNonCurrentLiabilities DECIMAL(15,2) NULL,
    TotalShareholderEquity DECIMAL(15,2) NULL,
    TreasuryStock DECIMAL(15,2) NULL,
    RetainedEarnings DECIMAL(15,2) NULL,
    CommonStock DECIMAL(15,2) NULL,
    CommonStockSharesOutstanding DECIMAL(15,2) NULL,

    Constraint FK_BalanceSheet_Stock FOREIGN KEY (StockId) 
    REFERENCES Entity.Stock(Id)
)